In [25]:
# Importing libraries
import pandas as pd

In [26]:
# 불량량 Loading
Defect_WT = pd.read_csv('defect_hangul.csv', encoding='cp949')
Defect_WT.head()

,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,강종그룹,강종코드,...,압연공정4,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량
0,2023-01-07,2,9,S52465,B2C0638202,D23W1W0141,60,T,SSB,SSB036,...,NaN,NaN,0.0,0,8100,2023-01-04,D,2023-02-02,NaN,NaN
1,2023-01-07,2,9,S52741,B310050902,D23W1W0369,60,T,SSB,SSB039,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN
2,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,T,SSB,SSB039,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
3,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,T,SSB,SSB039,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
4,2023-01-08,2,9,S52741,B310051009,D23W1W0369,62,T,SSB,SSB039,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN

In [27]:
# 중강종 파생변수 생성코드
Defect_WT['중강종'] = Defect_WT['강종그룹'].str[0:2]
# STEEL_GROUP_L는 Steel Grade 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('강종그룹')
Defect_WT.insert(position, '중강종', Defect_WT.pop('중강종'))

# 대강종 파생변수 생성코드
Defect_WT['대강종'] = Defect_WT['강종그룹'].str[0]
# 대강종은 중강종 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('중강종')
Defect_WT.insert(position, '대강종', Defect_WT.pop('대강종'))

Defect_WT.head()
#print(Defect_WT['대강종'])

,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,대강종,중강종,...,압연공정4,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량
0,2023-01-07,2,9,S52465,B2C0638202,D23W1W0141,60,T,S,SS,...,NaN,NaN,0.0,0,8100,2023-01-04,D,2023-02-02,NaN,NaN
1,2023-01-07,2,9,S52741,B310050902,D23W1W0369,60,T,S,SS,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN
2,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,T,S,SS,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
3,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,T,S,SS,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
4,2023-01-08,2,9,S52741,B310051009,D23W1W0369,62,T,S,SS,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN

In [28]:
# Year Month Date' 열을 datetime 형식으로 변환
Defect_WT['최종압연일자'] = pd.to_datetime(Defect_WT['최종압연일자'])

#압연월 구분
Defect_WT['압연월'] = Defect_WT['최종압연일자'].dt.month
#Defect_WT['압연월'] = Defect_WT['압연월'].fillna("", inplace=True)  # Fill missing values with "" (or any other appropriate value)

# 압연월은 년월 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('년월일')
Defect_WT.insert(position, '압연월', Defect_WT.pop('압연월'))

#압연년 구분
Defect_WT['압연년'] = Defect_WT['최종압연일자'].dt.year
#Defect_WT['압연년'] = Defect_WT['압연년'].fillna("", inplace=True)  # Fill missing values with "" (or any other appropriate value)

# 압연년은 압연월 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('압연월')
Defect_WT.insert(position, '압연년', Defect_WT.pop('압연년'))
Defect_WT.head()

,압연년,압연월,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,...,압연공정4,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량
0,2023,1,2023-01-07,2,9,S52465,B2C0638202,D23W1W0141,60,T,...,NaN,NaN,0.0,0,8100,2023-01-04,D,2023-02-02,NaN,NaN
1,2023,1,2023-01-07,2,9,S52741,B310050902,D23W1W0369,60,T,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN
2,2023,1,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,T,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
3,2023,1,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,T,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
4,2023,1,2023-01-08,2,9,S52741,B310051009,D23W1W0369,62,T,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN

In [29]:
# Check if '압연월' is empty and replace '압연분기' with a blank space
mask = Defect_WT['압연월'] == ""
Defect_WT.loc[mask, '압연분기'] = ""

# Calculate '압연분기' for rows with non-empty '압연월'
mask = Defect_WT['압연월'] != ""
Defect_WT.loc[mask, '압연분기'] = Defect_WT.loc[mask, '압연월'].apply(lambda month: '1Q' if month <= 3 else '2Q' if month <= 6 else '3Q' if month <= 9 else '4Q')

# 압연분기는 압연월 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('압연월')
Defect_WT.insert(position, '압연분기', Defect_WT.pop('압연분기'))

Defect_WT.head()
#print(Defect_WT['압연분기'])

,압연년,압연분기,압연월,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,...,압연공정4,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량
0,2023,1Q,1,2023-01-07,2,9,S52465,B2C0638202,D23W1W0141,60,...,NaN,NaN,0.0,0,8100,2023-01-04,D,2023-02-02,NaN,NaN
1,2023,1Q,1,2023-01-07,2,9,S52741,B310050902,D23W1W0369,60,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN
2,2023,1Q,1,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
3,2023,1Q,1,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
4,2023,1Q,1,2023-01-08,2,9,S52741,B310051009,D23W1W0369,62,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN

In [30]:
# 1,433처럼 중량에 콤마가 있는 Object는 콤마를 제거 후 숫자로 변환해야 함.
Defect_WT['발생중량'] = Defect_WT['발생중량'].str.replace(',', '').astype(int)
Defect_WT.head()

,압연년,압연분기,압연월,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,...,압연공정4,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량
0,2023,1Q,1,2023-01-07,2,9,S52465,B2C0638202,D23W1W0141,60,...,NaN,NaN,0.0,0,8100,2023-01-04,D,2023-02-02,NaN,NaN
1,2023,1Q,1,2023-01-07,2,9,S52741,B310050902,D23W1W0369,60,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN
2,2023,1Q,1,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
3,2023,1Q,1,2023-01-08,2,9,S52744,B310060208,E23W1W0126,70,...,NaN,NaN,0.0,0,8100,2023-01-06,D,2023-02-02,NaN,NaN
4,2023,1Q,1,2023-01-08,2,9,S52741,B310051009,D23W1W0369,62,...,NaN,NaN,0.0,0,8100,2023-01-06,C,2023-02-02,NaN,NaN

In [31]:
# 엑셀 파일로 저장
# pip install openpyxl 사전 설치 필요
output_path = 'pre_defect_data.xlsx'  # 저장할 파일 경로와 이름
Defect_WT.to_excel(output_path, index=False)  # index=False로 설정하여 인덱스를 엑셀에 포함하지 않음