In [1]:
# Importing libraries
import pandas as pd

In [2]:
# 불량량 Loading
Defect_WT = pd.read_csv('defect_316LDSB.csv', encoding='cp949')
Defect_WT.head()

,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,재료코드,강종그룹,...,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량,주설비구분
0,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,SSM,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
1,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,SSM,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
2,2023-07-24,2,9,S54204,B350698202,D23W7W1114,90,T,7730,SSM,...,NaN,0,0,8100,2023-07-23,B,2023-08-07,NaN,NaN,C
3,2024-04-29,2,9,S57283,B440412302,D24W3W1469,80,T,7730,SSM,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C
4,2024-04-29,2,9,S57283,B440412201,D24W4W1343,80,T,7730,SSM,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C

In [3]:
# 중강종 파생변수 생성코드
Defect_WT['중강종'] = Defect_WT['강종그룹'].str[0:2]
# STEEL_GROUP_L는 Steel Grade 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('강종그룹')
Defect_WT.insert(position, '중강종', Defect_WT.pop('중강종'))
Defect_WT.head()
#print(Defect_WT['중강종'])

,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,재료코드,중강종,...,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량,주설비구분
0,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,SS,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
1,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,SS,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
2,2023-07-24,2,9,S54204,B350698202,D23W7W1114,90,T,7730,SS,...,NaN,0,0,8100,2023-07-23,B,2023-08-07,NaN,NaN,C
3,2024-04-29,2,9,S57283,B440412302,D24W3W1469,80,T,7730,SS,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C
4,2024-04-29,2,9,S57283,B440412201,D24W4W1343,80,T,7730,SS,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C

In [4]:
# 대강종 파생변수 생성코드
Defect_WT['대강종'] = Defect_WT['강종그룹'].str[0]
# 대강종은 중강종 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('중강종')
Defect_WT.insert(position, '대강종', Defect_WT.pop('대강종'))
Defect_WT.head()

,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,재료코드,대강종,...,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량,주설비구분
0,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,S,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
1,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,S,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
2,2023-07-24,2,9,S54204,B350698202,D23W7W1114,90,T,7730,S,...,NaN,0,0,8100,2023-07-23,B,2023-08-07,NaN,NaN,C
3,2024-04-29,2,9,S57283,B440412302,D24W3W1469,80,T,7730,S,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C
4,2024-04-29,2,9,S57283,B440412201,D24W4W1343,80,T,7730,S,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C

In [5]:
# Year Month Date' 열을 datetime 형식으로 변환
Defect_WT['최종압연일자'] = pd.to_datetime(Defect_WT['최종압연일자'])

#압연월 구분
Defect_WT['압연월'] = Defect_WT['최종압연일자'].dt.month
#Defect_WT['압연월'] = Defect_WT['압연월'].fillna("", inplace=True)  # Fill missing values with "" (or any other appropriate value)

# 압연월은 년월 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('년월일')
Defect_WT.insert(position, '압연월', Defect_WT.pop('압연월'))
Defect_WT.head()

,압연월,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,재료코드,...,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량,주설비구분
0,9,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
1,9,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,7730,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
2,7,2023-07-24,2,9,S54204,B350698202,D23W7W1114,90,T,7730,...,NaN,0,0,8100,2023-07-23,B,2023-08-07,NaN,NaN,C
3,4,2024-04-29,2,9,S57283,B440412302,D24W3W1469,80,T,7730,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C
4,4,2024-04-29,2,9,S57283,B440412201,D24W4W1343,80,T,7730,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C

In [6]:
#압연년 구분
Defect_WT['압연년'] = Defect_WT['최종압연일자'].dt.year
#Defect_WT['압연년'] = Defect_WT['압연년'].fillna("", inplace=True)  # Fill missing values with "" (or any other appropriate value)

# 압연년은 압연월 컬럼 앞에 배치
position = Defect_WT.columns.get_loc('압연월')
Defect_WT.insert(position, '압연년', Defect_WT.pop('압연년'))
Defect_WT.head()

,압연년,압연월,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,...,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량,주설비구분
0,2023,9,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
1,2023,9,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
2,2023,7,2023-07-24,2,9,S54204,B350698202,D23W7W1114,90,T,...,NaN,0,0,8100,2023-07-23,B,2023-08-07,NaN,NaN,C
3,2024,4,2024-04-29,2,9,S57283,B440412302,D24W3W1469,80,T,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C
4,2024,4,2024-04-29,2,9,S57283,B440412201,D24W4W1343,80,T,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C

In [7]:
# 1,433처럼 중량에 콤마가 있는 Object는 콤마를 제거 후 숫자로 변환해야 함.
Defect_WT['발생중량'] = Defect_WT['발생중량'].str.replace(',', '').astype(int)
#Data_type = Defect_df['발생중량'].dtypes
#print(Data_type)

Defect_WT.head()

,압연년,압연월,년월일,업무구분,공장구분,HEAT_NO,LOT_NO,PON,공정순위,주조구분,...,압연일자4,압연외경4,압연폭4,최종압연공정,최종압연일자,제품압연작업조,생성일시,HCR,투입중량,주설비구분
0,2023,9,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
1,2023,9,2023-09-22,2,9,S54805,B360593201,D23W9W1414,80,T,...,NaN,0,0,8100,2023-09-21,B,2023-10-05,NaN,NaN,C
2,2023,7,2023-07-24,2,9,S54204,B350698202,D23W7W1114,90,T,...,NaN,0,0,8100,2023-07-23,B,2023-08-07,NaN,NaN,C
3,2024,4,2024-04-29,2,9,S57283,B440412302,D24W3W1469,80,T,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C
4,2024,4,2024-04-29,2,9,S57283,B440412201,D24W4W1343,80,T,...,NaN,0,0,8100,2024-04-28,C,2024-05-03,NaN,NaN,C

In [8]:
# 엑셀 파일로 저장
# pip install openpyxl 사전 설치 필요
output_path = 'pre_defect_316LDSB.xlsx'  # 저장할 파일 경로와 이름
Defect_WT.to_excel(output_path, index=False)  # index=False로 설정하여 인덱스를 엑셀에 포함하지 않음